# This is a basic workflow to help you get started with Actions
name: Test

on:
  push:
  pull_request:

jobs:
  Tests:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3

      - name: Xcode Select Version
        uses: mobiledevops/xcode-select-version-action@v1
        with:
          xcode-select-version: 14.2
  
      - name: Install xcbeautify
        run: brew install xcbeautify

      - name: Run unit tests
        run: xcodebuild -scheme MeetingBar test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcbeautify
